### ISSUE TITLE
Schema update for Readers, Cycle times, and Plot types

### ISSUE THREAD

**Issue by brandonzhu09** [JCSDA-internal/evagram#25]
## Description

Schema update for the addition of the eva reader, cycle times, and plot types.

## Schema

![Evagram-Final drawio (2)](https://github.com/JCSDA-internal/evagram/assets/38299259/549d1582-4289-49a8-8777-51e323cff2d9)

**Comment by brandonzhu09** [comment]
![Evagram-2 drawio](https://github.com/JCSDA-internal/evagram/assets/38299259/a9fade82-9d43-4f77-8133-c77c8d41d9d9)

Here is the new schema from our discussion last time!

**Comment by ghost** [comment]
Make `plot_type` an ENUM with a limited set of acceptable values, not varchar

**Comment by ghost** [comment]
Shall we take this opportunity to add an attribute to Experiments called something like `CREATE_DATE` ?

**Comment by asewnath** [comment]
> Shall we take this opportunity to add an attribute to Experiments called something like `CREATE_DATE` ?

Is that what `timestamp` is?

**Comment by ghost** [comment]
@asewnath I wasn't sure if that referred to cycle point/s or not.

**Comment by ghost** [comment]
In a past meeting, I proposed a different structure for the `Readers` table.  The idea was to convert `Readers` from wide format to long format, for example:

```
reader_name    alias_name    alias_value                                           
IodaObsSpace   Observation   Observation  * (trivial alias, no actual change) 
IodaObsSpace   Group         Plots                                                 
IodaObsSpace   Variable      Variable     *                                      
SocaRestart    Observation   SOCA                                                  
SocaRestart    Group         SocaVars                                              
SocaRestart    Variable      Variable     *                                      
JediLog        Observation   JediLog                                               
JediLog        Group         Log Options                                           
JediLog        Variable      Variable     *
```

Reasoning:
This generic solution is more robust against future schema changes.  Generally speaking, I avoid naming table columns after other tables.  The `Readers` table defines aliases for attributes of the `Plots` table.  Right now there are 3 attributes (observation, variable, group).  One day there might be 4 attributes to alias.  One day we might want to use a different word than "group".  In both cases, we'd have to alter the `Readers` schema to account for those changes, and perhaps backfill empty cells.  Ideally, we should reduce or eliminate the need for interdependent schema changes.  If `Readers` has a long format, at most we may need update, remove, or add rows to it.  It is much safer and more sustainable to update the records in a table rather than the table's schema itself.  Back-end Python code will have fewer reasons to change as well, because it can use `Readers`, in long form, as a generalized lookup table.  `Readers` will never grow exceedingly large, so it should remain manageable even in a long format.

**Comment by ghost** [comment]
@brandonzhu09  As discussed earlier, please change the name of `timestamp` to `creation_date` and make it a `timestamp` data type.  The schema should automatically insert the datetime with the `current_timestamp` function.

EDIT:  `current_timestamp` is an internal postgres function

**Comment by brandonzhu09** [comment]
![Evagram-Final drawio](https://github.com/JCSDA-internal/evagram/assets/38299259/63558824-e4d7-4d4e-a0f4-59b24f62edfa)

New schema update!

**Comment by ghost** [comment]
1.  Remove relationship between Readers and Experiments.
2. Make cycle_time (in Plots) a datetime (still keeping in mind the time series issue)
3. Draft the schema changes into the django backend.  When user selects an Experiment, execute logic that scans Plots to get a unique set of Readers for that table.  Force the user to select 1 (or NULL?).  Upon selection, lookup the Readers table and get all the aliases.  Then apply the aliases.

**Comment by brandonzhu09** [comment]
![Evagram-Final drawio (1)](https://github.com/user-attachments/assets/402a9585-8240-4211-aee7-3d523b8e20e3)

Here is the finalized schema change following Tariq's last comment. I also added the Aliases table since it would be necessary to keep track of all the aliases associated with a single reader. I will begin updating the models in Django to the latest version of the schema!
